/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Azure-inspired hierarchical documentation structure
  docsSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Overview'
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'theoretical'
        }
      ]
    },
    {
      type: 'category', 
      label: 'SUI Integration',
      collapsible: true,
      collapsed: false,
      items: [
        'sui-integration/overview',
        {
          type: 'category',
          label: 'Smart Contracts',
          collapsible: true,
          collapsed: true,
          items: [
            'sui-integration/smart-contracts/overview',
            'sui-integration/smart-contracts/deployment',
            'sui-integration/smart-contracts/integration',
            'sui-integration/smart-contracts/testing'
          ]
        },
        {
          type: 'category',
          label: 'Authentication',
          collapsible: true, 
          collapsed: true,
          items: [
            'sui-integration/authentication/zklogin',
            'sui-integration/authentication/prover-service'
          ]
        },
        {
          type: 'category',
          label: 'Encryption & Storage',
          collapsible: true,
          collapsed: true,
          items: [
            'sui-integration/encryption/seal',
            'sui-integration/storage/walrus'
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Implementation Guides',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'implementation'
        }
      ]
    }
  ],
};

module.exports = sidebars;