/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Autogenerate the sidebar from the folder structure
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from the docs root folder
    },
  ],
};

module.exports = sidebars;